config/routes.rb
Rails.application.routes.draw do
    root 'pages#home'
    get 'about', to: 'pages#about'
    resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: { minimum: 6 , maximum: 100 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :find_article, only: [:show, :edit, :update, :destroy]

    def show
    end

    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def edit
    end

    def create
        @article = Article.new(params_article)
        if @article.save
            flash[:notice] = "Article successfully created."
            redirect_to @article
        else
            render 'new'
        end
    end

    def update
        if @article.update(params_article)
            flash[:notice] = "Article successfully edited."
            redirect_to @article
        else
            render 'edit'
        end
    end

    def destroy
        if @article.destroy
            flash[:notice] = "Article successfully deleted"
            redirect_to @article
        end
    end

    private

    def find_article
        @article = Article.find(params[:id])
    end

    def params_article
        params.require(:article).permit(:title, :description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.erb
<% if @article.errors.any? %>
    <h2>The following errors stop the article from being edited<h3>
        <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
<% end %>

<%= form_with(model: @article, local: true) do |f| %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :description %><br>
        <%= f.text_area :description %>
    </p>
    <p>
        <%= f.submit %>
    </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<p>
    <%= link_to 'Cancel and return to the listing of articles', articles_path%>
</p>

app/views/articles/index.html.erb
<h1>Articles page</h1>

<table>
    <thead>
        <tr>
            <td>Title</td>
            <td>Description</td>
            <td colspan="3">Placeholder</td>
        </tr>
    </thead>
    <tbody>
    <% @articles.each do |article| %>
        <tr>
            <td><%= article.title %></td>
            <td><%= article.description %></td>
            <td><%= link_to 'Show', article_path(article) %></td>
            <td><%= link_to 'Edit', edit_article_path(article) %></td>
            <td><%= link_to 'Delete', article_path(article), method: :Delete, data: { confirm:"Are you sure?" } %></td>
        </tr>
        <% end %>
    </tbody>
</table><br>

<%= button_to 'Create a new article' , new_article_path, method: :get %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Cancel and return to the listing of articles', articles_path, data: { confirm:"Are you sure?" }%>

app/views/articles/show.html.erb
<h1>ARTICLES</h1>

<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>

<p>
    <%= link_to 'Return to listing page', articles_path %> | 
    <%= link_to 'Edit', edit_article_path(@article) %> | 
    <%= link_to 'Delete', article_path(@article), method: :Delete, data: {confirm: "Are you sure?"} %>
</p>

app/views/layouts/_message.html.erb
<% flash.each do |notice, msg| %>
    <%= msg %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/message' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the ABOUT page</h1>

<%= link_to 'Articles list', articles_path %> |
<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<h1>This is the HOME page</h1>

<%= link_to 'Articles list', articles_path %> |
<%= link_to 'About page', about_path %>